name: Build CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'            
      - '.gitignore'    
      - 'LICENSE'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'            
      - '.gitignore'    
      - 'LICENSE'

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Python setup
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Initial file
      run: |
        mkdir -p include
        echo '#ifndef KEY_H' > include/key.h
        echo '#define KEY_H' >> include/key.h
        echo '#define SSID "dummy"' >> include/key.h
        echo '#define PASSWORD "dummy"' >> include/key.h
        echo '#define API_KEY "dummy"' >> include/key.h
        echo '#define DATABASE_URL "dummy"' >> include/key.h
        echo '#define HERE_API_KEY "dummy"' >> include/key.h
        echo '#endif' >> include/key.h

    - name: PlatformIO Core
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio

    - name: Compile
      run: pio run -e nodemcu-32s

    - name: Run Unit Tests
      run: pio test -e native

    - name: Packaging firmware
      uses: actions/upload-artifact@v4
      with:
        name: esp32-gps-tracker-firmware 
        path: |
          .pio/build/nodemcu-32s/firmware.bin
          .pio/build/nodemcu-32s/partitions.bin
        retention-days: 7 