name: Auto Format Code

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cài đặt Clang-Format
        run: sudo apt-get install -y clang-format

      - name: Chạy Format tự động
        run: |
          find src include -name '*.cpp' -o -name '*.h' | xargs clang-format -i -style=file

      - name: Tự động Commit và Push ngược lên Github
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: tự động format code chuẩn Google"