name: Check Code Formatting

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clang-Format Check
        uses: cpp-linter/cpp-linter-action@v2
        id: linter
        with:
          style: 'file' 
          tidy-checks: '' 
          thread-comments: true 
          files-changed-only: false 

      - name: Formatting checks failed
        if: steps.linter.outputs.checks-failed > 0
        run: |
          echo "LỖI: Wrong format detected in the codebase."
          exit 1